Ensure all prerequisite are available at startup
While here, do not pedantically request the file to be built to be
absent before processing.

diff --git a/build-image b/build-image
--- a/build-image
+++ b/build-image
@@ -12,9 +12,13 @@ if [ $(id -u) -ne 0 ]; then
 	exit 1
 fi
 
-if [ -f $image ]; then
-	echo "File exists: $image" >&2
+if [ ! -f /tmp/eVe.tgz ]; then
+	echo "File not found: /tmp/eVe.tgz" >&2
 	exit 1
+fi
+
+if [ -f $image ]; then
+	rm -f $image
 fi
 
 set -ex
